services:
  postgres:
    image: 'postgres:latest'
    container_name: testphonebooking-db
    environment:
      - 'POSTGRES_DB=testphonebooking'
      - 'POSTGRES_PASSWORD=d8a10358-32bc-46ab-9a59-472ad1156d41'
      - 'POSTGRES_USER=testphonebooking'
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./docker-entrypoint-initdb.d/db.sql:/docker-entrypoint-initdb.d/db.sql
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fdobrotv.com
      PGADMIN_DEFAULT_PASSWORD: 9a45ac97-7544-4ca8-83f0-595b9b5f42a4
    volumes:
      - pgadmin:/var/lib/pgadmin
  api-editor:
    image: swaggerapi/swagger-editor
    ports:
      - "8889:8080"
    environment:
      SWAGGER_FILE: /specs/test-phone-booking-v1.0.yaml
    volumes:
      - ./specs/test-phone-booking-v1.0.yaml:/specs/test-phone-booking-v1.0.yaml
volumes:
  pgdata:
  pgadmin: